

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_PATH=/app/rag_db
      - MODEL_NAME=llama3.2:1b
    volumes:
      - chroma_data:/app/rag_db
      - ./docs:/app/docs
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

volumes:
  chroma_data:
  ollama_models: